### ISSUE TITLE
#TK Modificar los Milestones (deben quedar los tres correspondientes a los Sprints 0, 1 y 2).

### ISSUE THREAD

**Issue by NoeCoast** [Dev-Full-Solutions/AnalizArApp#86]
@NoeCoast 

- [x] Revisar cuáles fueron las observaciones en las correcciones del Sprint anterior.
- [x] Crear TK para documentar las acciones solicitadas y que quede registro de ello.
- [x] Revisar los Milestones que figuran actualmente.
- [x] Incorporar los Milestones solicitados.
- [x] Comunicar la actualización de los Milestones
- [x] Realizar y cerrar tarea.
