### ISSUE TITLE
#TK Eliminar los Milestones erróneos.

### ISSUE THREAD

**Issue by NoeCoast** [Dev-Full-Solutions/AnalizArApp#87]
@NoeCoast 

- [x] Revisar e identificar los Milestones erróneos.
- [x] Crear TK para documentar las acciones solicitadas y que quede registro de ello.
- [x] Asegurarse de preoceder de manera cuidadosa para eliminarlos
- [x] Comprobar que fueron eliminados correctamente.
- [x] Asegurarse  que en la documentación o registros relacionados se actualicen de manera correcta y reflejen los cambios.  
- [x] Comunicar la actualización de los Milestones
- [x] Realizar y cerrar tarea.
